name: Build Pipeline
run-name: Jay's Build Pipeline 
on:
  workflow_dispatch:
    inputs:
      build-push-image:
        type: boolean
        description: Build and Push the Image
  push:
    branches:    
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: mvn build
    - run: echo 'running SCA'
    - run: echo 'running linting'
    - run: echo 'running format check'
    - run: echo 'running security scanning'
    - run: echo 'running export test reports'
    - run: echo 'running export SCA reports'

  terraform-run:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'running terraform linting'
    - run: echo 'running terraform format check'
    - run: echo 'running security scanning'

    - run: echo 'terraform init'
    - run: echo 'terraform validate'

  build-push-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: echo 'build push image'