name: Build Pipeline
run-name: Jay's Build Pipeline 
on:
  workflow_dispatch:
    inputs:
      build-push-image:
        type: boolean
        description: Build and Push the Image
  push:
    branches:    
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Check Java version
      run: java --version 

    - name: Running Unit Test
      run: echo 'unit testing'

    - name: Running SCA
      run: echo 'sca'

    - name: mvn clean install
      run: mvn clean install

    - name: mvn package
      run: mvn package

    - name: Running linting
      run: echo 'linting'

    - name: Running format check
      run: echo 'format check'

    - name: Security Scanning
      run: echo 'security scanning'

    - name: Export Test Reports
      run: echo 'export test reports'

    - name: Export SCA reports
      run: echo 'export SCA reports'

  terraform-run:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'running terraform linting'
    - run: echo 'running terraform format check'
    - run: echo 'running security scanning'

    - run: echo 'terraform init'
    - run: echo 'terraform validate'

  # Create image and push to container registry
  build-push-image: 
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}
        cache-from: type=gha
        cache-to: type=gha,mode=max